FROM python:3.4
RUN apt-get update
